/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Diagnosis: { // root type
    code?: string | null; // String
    id: string; // String!
    latin?: string | null; // String
    name?: string | null; // String
  }
  Mutation: {};
  Patient: { // root type
    dateOfBirth?: string | null; // String
    gender?: string | null; // String
    id: string; // String!
    name?: string | null; // String
    occupation?: string | null; // String
    ssn?: string | null; // String
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Diagnosis: { // field return type
    code: string | null; // String
    id: string; // String!
    latin: string | null; // String
    name: string | null; // String
  }
  Mutation: { // field return type
    createPatient: NexusGenRootTypes['Patient']; // Patient!
  }
  Patient: { // field return type
    dateOfBirth: string | null; // String
    gender: string | null; // String
    id: string; // String!
    name: string | null; // String
    occupation: string | null; // String
    ssn: string | null; // String
  }
  Query: { // field return type
    diagnoses: Array<NexusGenRootTypes['Diagnosis'] | null> | null; // [Diagnosis]
    patient: NexusGenRootTypes['Patient'] | null; // Patient
    patients: Array<NexusGenRootTypes['Patient'] | null> | null; // [Patient]
  }
}

export interface NexusGenFieldTypeNames {
  Diagnosis: { // field return type name
    code: 'String'
    id: 'String'
    latin: 'String'
    name: 'String'
  }
  Mutation: { // field return type name
    createPatient: 'Patient'
  }
  Patient: { // field return type name
    dateOfBirth: 'String'
    gender: 'String'
    id: 'String'
    name: 'String'
    occupation: 'String'
    ssn: 'String'
  }
  Query: { // field return type name
    diagnoses: 'Diagnosis'
    patient: 'Patient'
    patients: 'Patient'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createPatient: { // args
      dateOfBirth: string; // String!
      gender: string; // String!
      name: string; // String!
      occupation: string; // String!
      ssn: string; // String!
    }
  }
  Query: {
    patient: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}